### ISSUE TITLE
calibrate data issue

### ISSUE THREAD

**Issue by Yutao-Jin** [awsiuk/ENS160#3]
Thank you for this amazing library.
I was wondering in the datasheet, they specify the temp data should be (temp + 273.15) * 64.0 + 0.5, but i did not see any conversion like this in the library, the same thing also applies to the humidity data.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/71048891/229569079-b01a2c7a-5279-4210-ad1b-52e9f18bf2b5.png">

**Comment by awsiuk** [comment]
Hi,

There is byte shift by 8bits for temperature which gives multiplication by 64. but indeed calculation is missing. This needs to be fixed.

**Comment by awsiuk** [comment]
i have no longer ENS160 but it should work with the changes in the code. Code updated with your notes.
Thanks!

**Comment by Yutao-Jin** [comment]
Thank you so much

**Comment by Yutao-Jin** [comment]
Sorry to bother you again, have you encountered this issue, that the ens160 outputs good data when first powered up but after the initial start-up the when the VALIDITY FLAG goes to 0, which meas normal operation it just outputs 0 for all data
<img width="957" alt="image" src="https://user-images.githubusercontent.com/71048891/231311270-96cbd5ae-6625-438d-910b-56b6a928596d.png">

![](https://user-images.githubusercontent.com/71048891/231310863-828d2c8b-2f2a-47da-9cd0-d62e41cc9da1.png)
